-- 1부: 회원 / 설정 / 홈(지도·검색·랭킹) / 팝업 / 게시판
-- ------------------------------------------------------------
-- -- 0. 회원 (마이페이지 / 활동 주체)
-- ------------------------------------------------------------
DROP USER TKK CASCADE ;
CREATE USER TKK
    IDENTIFIED BY kosmo1234
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

------------------------------------------------------------
-- 2. 권한 부여 (수업용 전형적인 설정)
------------------------------------------------------------
-- 기본 접속 및 객체 생성 권한
GRANT CREATE SESSION TO TKK;
GRANT CREATE TABLE TO TKK;
GRANT CREATE VIEW TO TKK;
GRANT CREATE SEQUENCE TO TKK;
GRANT CREATE TRIGGER TO TKK;
GRANT CREATE PROCEDURE TO TKK;

-- 예전부터 많이 쓰던 CONNECT, RESOURCE 롤도 같이 줌(학원 환경에서 자주 사용)
GRANT CONNECT, RESOURCE TO TKK;


CREATE TABLE TKK.MEMBER (
                            member_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id          VARCHAR2(50)   NOT NULL UNIQUE,
    login_pw          VARCHAR2(255)  NOT NULL,
    nickname          VARCHAR2(50)   NOT NULL UNIQUE,
    profile_image_url VARCHAR2(255),
    intro             VARCHAR2(255),
    user_level        NUMBER          DEFAULT 1,
    email             VARCHAR2(100),
    gender            VARCHAR2(10)   NOT NULL,
    nationality       VARCHAR2(10)   NOT NULL,
    created_at        DATE            DEFAULT SYSDATE,
    updated_at        DATE,
    deleted_yn        CHAR(1)         DEFAULT 'N',

    /* ENUM처럼 동작하게 제약조건 추가 */
    CONSTRAINT chk_member_gender
        CHECK (gender IN ('남자', '여자')),

    CONSTRAINT chk_member_nationality
        CHECK (nationality IN ('내국인', '외국인'))
    );
--
-- ------------------------------------------------------------
-- -- 0-1. 회원 알림 설정 (알림 ON/OFF)
-- ------------------------------------------------------------
CREATE TABLE TKK.member_notification_setting (
                                             member_id   NUMBER      PRIMARY KEY,                   -- 회원 PK (member와 1:1)
                                             comment_yn  CHAR(1)    DEFAULT 'Y',                    -- 댓글/답글 알림
                                             like_yn     CHAR(1)    DEFAULT 'Y',                    -- 좋아요 알림
                                                                -- 좋아요 알림
                                             trade_yn    CHAR(1)    DEFAULT 'Y',                    -- 거래 관련 알림
                                             event_yn    CHAR(1)    DEFAULT 'Y',                    -- 이벤트/팝업 알림
                                             created_at  DATE       DEFAULT SYSDATE,                -- 생성일
                                             updated_at  DATE,                                      -- 수정일
                                             CONSTRAINT fk_mns_member FOREIGN KEY (member_id)
                                                 REFERENCES TKK.member(member_id) ON DELETE CASCADE
);
--
-- ------------------------------------------------------------
-- -- 1. 매장 / 지도 / 랭킹 / 검색
-- ------------------------------------------------------------
CREATE TABLE TKK.store (
                       store_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 매장 PK
                       name            VARCHAR2(100)  NOT NULL,                             -- 매장명
                       one_line_desc   VARCHAR2(200),                                       -- 한 줄 설명
                       address         VARCHAR2(255),                                       -- 전체 주소
                       region_name     VARCHAR2(100),                                       -- 지역명 (예: 홍대, 강남)
                       latitude        NUMBER(11, 8),                                       -- 위도
                       longitude       NUMBER(11, 8),                                       -- 경도
                       avg_rating      NUMBER(3, 2)   DEFAULT 0,                            -- 평균 평점
                       bookmark_count  NUMBER         DEFAULT 0,                            -- 즐겨찾기 수

                       phone           VARCHAR2(30),                                        -- 연락처
                       created_at      DATE           DEFAULT SYSDATE                       -- 등록일
);
--
-- 매장 즐겨찾기 (북마크)
CREATE TABLE TKK.store_bookmark (
                                store_bookmark_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 굿즈 PK
                                member_id   NUMBER NOT NULL,                         -- 회원 ID
                                store_id    NUMBER NOT NULL,                         -- 매장 ID
                                created_at  DATE   DEFAULT SYSDATE,                  -- 즐겨찾기 추가일
                                CONSTRAINT uk_store_bookmark UNIQUE (member_id, store_id),
                                CONSTRAINT fk_sb_member FOREIGN KEY (member_id)
                                    REFERENCES TKK.member(member_id),
                                CONSTRAINT fk_sb_store FOREIGN KEY (store_id)
                                    REFERENCES TKK.store(store_id)
);
--
-- -- 매장별 굿즈 (매장 상세 상품 리스트/재고)
CREATE TABLE TKK.store_goods (
                             goods_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 굿즈 PK
                             store_id        NUMBER       NOT NULL,                               -- 매장 ID
                             name            VARCHAR2(150) NOT NULL,                              -- 굿즈 이름
                             work_name       VARCHAR2(100),                                       -- 작품명
                             character_name  VARCHAR2(100),                                       -- 캐릭터명
                             category        VARCHAR2(30),                                        -- 카테고리 (포카/피규어/앨범 등)
                             price           NUMBER,                                              -- 가격
                             stock_qty       NUMBER,                                              -- 재고 수량
                             thumbnail_url   VARCHAR2(255),                                       -- 썸네일 이미지
                             created_at      DATE DEFAULT SYSDATE,                                -- 등록일
                             updated_at      DATE,                                                -- 수정일
                             CONSTRAINT fk_sg_store FOREIGN KEY (store_id)
                                 REFERENCES TKK.store(store_id)
);
--
-- -- 검색 로그 (실시간 검색 랭킹, 최근/인기 검색어)
CREATE TABLE TKK.search_log (
                            search_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 검색 로그 PK
                            member_id   NUMBER,                                              -- 검색한 회원 (비회원 NULL)
                            keyword     VARCHAR2(100) NOT NULL,                             -- 검색어
                            target_type VARCHAR2(20),                                       -- STORE / GOODS 등
                            target_id   NUMBER,                                             -- 대상 ID (store_id, goods_id 등)
                            created_at  DATE DEFAULT SYSDATE,                               -- 검색 시각
                            CONSTRAINT fk_sl_member FOREIGN KEY (member_id)
                                REFERENCES TKK.member(member_id)
);
--
-- -- 추천 검색어(관리자가 등록하는 추천 키워드)
CREATE TABLE TKK.recommended_search (
                                    rec_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 추천 검색어 PK
                                    keyword     VARCHAR2(100) NOT NULL,                              -- 추천 키워드
                                    target_type VARCHAR2(20),                                        -- STORE / GOODS 등
                                    sort_order  NUMBER DEFAULT 1,                                    -- 노출 순서
                                    active_yn   CHAR(1) DEFAULT 'Y'                                  -- 사용 여부
);
--
-- ------------------------------------------------------------
-- -- 2. 팝업스토어 / 메인 배너
-- ------------------------------------------------------------

CREATE TABLE TKK.popup_store (
                             popup_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 팝업스토어 PK
                             title           VARCHAR2(150) NOT NULL,                              -- 팝업 이름
                             place_name      VARCHAR2(150),                                       -- 장소 이름
                             address         VARCHAR2(255),                                       -- 주소
                             region_name     VARCHAR2(100),                                       -- 지역명 (예: 홍대)
                             latitude        NUMBER(11, 8),                                       -- 위도
                             longitude       NUMBER(11, 8),                                       -- 경도
                             start_date      DATE        NOT NULL,                                -- 시작일
                             end_date        DATE        NOT NULL,                                -- 종료일
                             banner_image_url VARCHAR2(255),                                      -- 배너 이미지
                             description     CLOB,                                                -- 상세 설명
                             created_at      DATE        DEFAULT SYSDATE                          -- 등록일
);


-- -- 팝업스토어 찜
CREATE TABLE TKK.popup_bookmark (
                                popup_bookmark_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 팝업스토어 PK
                                member_id   NUMBER NOT NULL,                      -- 회원 ID
                                popup_id    NUMBER NOT NULL,                      -- 팝업 ID
                                created_at  DATE   DEFAULT SYSDATE,               -- 찜 추가일
                                CONSTRAINT uk_popup_bookmark UNIQUE (member_id, popup_id),
                                CONSTRAINT fk_pb_member FOREIGN KEY (member_id)
                                    REFERENCES TKK.member(member_id),
                                CONSTRAINT fk_pb_popup FOREIGN KEY (popup_id)
                                    REFERENCES TKK.popup_store(popup_id)
);
--
--
--
-- -- 팝업 굿즈 정보 (팝업 전용 굿즈 리스트)
CREATE TABLE TKK.popup_goods (
                             popup_goods_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 팝업 굿즈 PK
                             popup_id        NUMBER NOT NULL,                                     -- 팝업 ID
                             name            VARCHAR2(150) NOT NULL,                              -- 굿즈 이름
                             description     VARCHAR2(255),                                       -- 간단 설명
                             category        VARCHAR2(30),                                        -- 카테고리
                             price           NUMBER,                                              -- 가격
                             thumbnail_url   VARCHAR2(255),                                       -- 이미지
                             CONSTRAINT fk_pg_popup FOREIGN KEY (popup_id)
                                 REFERENCES TKK.popup_store(popup_id)
);
--
-- -- 메인 배너 (팝업/이벤트 자동 슬라이드 배너)
CREATE TABLE TKK.main_banner (
                             banner_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 배너 PK
                             title           VARCHAR2(150) NOT NULL,                              -- 배너 제목
                             image_url       VARCHAR2(255) NOT NULL,                              -- 배너 이미지 URL
                             link_type       VARCHAR2(20),                                        -- POPUP / EVENT / URL 등
                             link_target_id  NUMBER,                                              -- 링크 대상 ID (popup_id, notice_id 등)
                             link_url        VARCHAR2(255),                                       -- 외부/내부 링크 URL
                             start_date      DATE,                                                -- 노출 시작일
                             end_date        DATE,                                                -- 노출 종료일
                             sort_order      NUMBER       DEFAULT 1,                              -- 정렬 순서
                             active_yn       CHAR(1)      DEFAULT 'Y'                             -- 사용 여부
);
--
-- ------------------------------------------------------------
-- -- 3. 덕질게시판 (내 새끼 자랑 / 코스프레 / 자유)
-- ------------------------------------------------------------
CREATE TABLE TKK.board_category (
                                category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 카테고리 PK
                                code        VARCHAR2(30)  NOT NULL UNIQUE,                       -- 코드(MY_GOODS, COSPLAY, FREE 등)
                                name        VARCHAR2(50)  NOT NULL                               -- 카테고리 이름
);

CREATE TABLE TKK.board_post (

                            post_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 게시글 PK
                            category_id     NUMBER       NOT NULL,                               -- 카테고리 ID
                            member_id       NUMBER       NOT NULL,                               -- 작성자 ID
                            title           VARCHAR2(200) NOT NULL,                              -- 제목
                            content         CLOB          NOT NULL,                              -- 본문
                            thumbnail_url   VARCHAR2(255),                                       -- 썸네일 이미지
                            view_count      NUMBER       DEFAULT 0,                              -- 조회수
                            like_count      NUMBER       DEFAULT 0,                              -- 좋아요 수
                            comment_count   NUMBER       DEFAULT 0,                              -- 댓글 수
                            created_at      DATE         DEFAULT SYSDATE,                        -- 작성일
                            updated_at      DATE,                                                -- 수정일
                            deleted_yn      CHAR(1)      DEFAULT 'N',                            -- 삭제 여부
                            CONSTRAINT fk_bp_category FOREIGN KEY (category_id)
                                REFERENCES TKK.board_category(category_id),
                            CONSTRAINT fk_bp_member FOREIGN KEY (member_id)
                                REFERENCES TKK.member(member_id)
);
--
-- 태그 (작품명, 캐릭터명 등)
CREATE TABLE TKK.board_tag (
                           tag_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 태그 PK
                           tag_name    VARCHAR2(50) NOT NULL UNIQUE                         -- 태그 이름
);
--
-- -- 게시글-태그 매핑
CREATE TABLE TKK.board_post_tag (
                                board_post_tag_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                post_id     NUMBER NOT NULL,                   -- 게시글 ID
                                tag_id      NUMBER NOT NULL,                   -- 태그 ID
                                CONSTRAINT uk_board_post_tag UNIQUE (post_id, tag_id),
                                CONSTRAINT fk_bpt_post FOREIGN KEY (post_id)
                                    REFERENCES TKK.board_post(post_id),
                                CONSTRAINT fk_bpt_tag FOREIGN KEY (tag_id)
                                    REFERENCES TKK.board_tag(tag_id)
);
--
-- 게시글 이미지
CREATE TABLE TKK.board_post_image (
                                  image_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 이미지 PK
                                  post_id     NUMBER NOT NULL,                                     -- 게시글 ID
                                  image_url   VARCHAR2(255) NOT NULL,                              -- 이미지 URL
                                  sort_order  NUMBER DEFAULT 1,                                    -- 정렬 순서
                                  CONSTRAINT fk_bpi_post FOREIGN KEY (post_id)
                                      REFERENCES TKK.board_post(post_id)
);
--
-- -- 댓글 (대댓글 포함)
CREATE TABLE TKK.board_comment (
                               comment_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 댓글 PK
                               post_id          NUMBER NOT NULL,                                     -- 게시글 ID
                               member_id        NUMBER NOT NULL,                                     -- 작성자 ID
                               parent_comment_id NUMBER,                                             -- 부모 댓글 ID(대댓글)
                               content          VARCHAR2(1000) NOT NULL,                             -- 댓글 내용
                               like_count       NUMBER DEFAULT 0,                                    -- 좋아요 수
                               created_at       DATE   DEFAULT SYSDATE,                              -- 작성일
                               updated_at       DATE,                                                -- 수정일
                               deleted_yn       CHAR(1) DEFAULT 'N',                                 -- 삭제 여부
                               CONSTRAINT fk_bc_post FOREIGN KEY (post_id)
                                   REFERENCES TKK.board_post(post_id),
                               CONSTRAINT fk_bc_member FOREIGN KEY (member_id)
                                   REFERENCES TKK.member(member_id),
                               CONSTRAINT fk_bc_parent FOREIGN KEY (parent_comment_id)
                                   REFERENCES TKK.board_comment(comment_id)
);
-- 게시글 좋아요
CREATE TABLE TKK.board_like (
                            board_like_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            member_id   NUMBER NOT NULL,                      -- 회원 ID
                            post_id     NUMBER NOT NULL,                      -- 게시글 ID
                            created_at  DATE   DEFAULT SYSDATE,               -- 좋아요 일시
                            CONSTRAINT uk_board_like UNIQUE(member_id, post_id),
                            CONSTRAINT fk_bl_member FOREIGN KEY (member_id)
                                REFERENCES TKK.member(member_id),
                            CONSTRAINT fk_bl_post FOREIGN KEY (post_id)
                                REFERENCES TKK.board_post(post_id)
);

-- -- 게시글 북마크(찜)
CREATE TABLE TKK.board_bookmark (
                                board_bookmark_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                member_id   NUMBER NOT NULL,                      -- 회원 ID
                                post_id     NUMBER NOT NULL,                      -- 게시글 ID
                                created_at  DATE   DEFAULT SYSDATE,               -- 북마크 일시
                                CONSTRAINT uk_board_bookmark UNIQUE(member_id, post_id),
                                CONSTRAINT fk_bb_member FOREIGN KEY (member_id)
                                    REFERENCES TKK.member(member_id),
                                CONSTRAINT fk_bb_post FOREIGN KEY (post_id)
                                    REFERENCES TKK.board_post(post_id)
);
--
-- -- 게시글/댓글 신고 기능
CREATE TABLE TKK.board_report (
                              report_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 신고 PK
                              post_id     NUMBER,                                              -- 신고 대상 게시글 ID
                              comment_id  NUMBER,                                              -- 신고 대상 댓글 ID
                              reporter_id NUMBER NOT NULL,                                     -- 신고한 회원 ID
                              reason      VARCHAR2(255),                                       -- 신고 사유
                              status      VARCHAR2(20) DEFAULT 'WAIT',                         -- 처리 상태 (WAIT/DONE 등)
                              created_at  DATE DEFAULT SYSDATE,                                -- 신고일
                              CONSTRAINT fk_br_post FOREIGN KEY (post_id)
                                  REFERENCES TKK.board_post(post_id),
                              CONSTRAINT fk_br_comment FOREIGN KEY (comment_id)
                                  REFERENCES TKK.board_comment(comment_id),
                              CONSTRAINT fk_br_member FOREIGN KEY (reporter_id)
                                  REFERENCES TKK.member(member_id)
);

-- 2부: 굿즈거래 / 채팅 / 알림 / FAQ / 문의 / 공지
--
-- ------------------------------------------------------------
-- -- 4. 굿즈거래 탭 (중고/교환 + 1:1 채팅)
-- ------------------------------------------------------------
CREATE TABLE TKK.trade_post (
                            trade_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 거래글 PK
                            seller_id       NUMBER       NOT NULL,                               -- 작성자(판매자) ID
                            title           VARCHAR2(200) NOT NULL,                              -- 글 제목
                            content         CLOB          NOT NULL,                              -- 내용
                            goods_name      VARCHAR2(150) NOT NULL,                              -- 굿즈 이름
                            work_name       VARCHAR2(100),                                       -- 작품명
                            character_name  VARCHAR2(100),                                       -- 캐릭터명
                            category        VARCHAR2(30),                                        -- 카테고리(포카/피규어/앨범 등)
                            price           NUMBER,                                              -- 가격
                            trade_type      VARCHAR2(20) NOT NULL,                               -- SELL/BUY/EXCHANGE
                            trade_method    VARCHAR2(20) NOT NULL,                               -- DIRECT/PAY 등
                            region          VARCHAR2(100),                                       -- 거래 지역
                            status          VARCHAR2(20) DEFAULT 'ON_SALE',                      -- ON_SALE/RESERVED/DONE
                            view_count      NUMBER       DEFAULT 0,                              -- 조회수
                            like_count      NUMBER       DEFAULT 0,                              -- 좋아요 수
                            created_at      DATE         DEFAULT SYSDATE,                        -- 작성일
                            updated_at      DATE,                                                -- 수정일
                            deleted_yn      CHAR(1)      DEFAULT 'N',                            -- 삭제 여부
                            CONSTRAINT fk_tp_member FOREIGN KEY (seller_id)
                                REFERENCES TKK.member(member_id)
);

-- 거래글 이미지
CREATE TABLE TKK.trade_post_image (
                                  image_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 이미지 PK
                                  trade_id    NUMBER NOT NULL,                                     -- 거래글 ID
                                  image_url   VARCHAR2(255) NOT NULL,                              -- 이미지 URL
                                  sort_order  NUMBER DEFAULT 1,                                    -- 정렬 순서
                                  CONSTRAINT fk_tpi_trade FOREIGN KEY (trade_id)
                                      REFERENCES TKK.trade_post(trade_id)
);

-- 거래글 찜/관심
CREATE TABLE TKK.trade_bookmark (
                                trade_bookmark_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 채팅방 PK

                                member_id   NUMBER NOT NULL,                      -- 회원 ID
                                trade_id    NUMBER NOT NULL,                      -- 거래글 ID
                                created_at  DATE   DEFAULT SYSDATE,               -- 찜 일시
                                CONSTRAINT uk_trade_bookmark UNIQUE(member_id, trade_id),
                                CONSTRAINT fk_tb_member FOREIGN KEY (member_id)
                                    REFERENCES TKK.member(member_id),
                                CONSTRAINT fk_tb_trade FOREIGN KEY (trade_id)
                                    REFERENCES TKK.trade_post(trade_id)
);
--
-- -- 거래 채팅방 (1:1)
CREATE TABLE TKK.trade_chat_room (
                                 room_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 채팅방 PK
                                 trade_id    NUMBER NOT NULL,                                     -- 거래글 ID
                                 seller_id    NUMBER NOT NULL,
                                 buyer_id    NUMBER NOT NULL,                                     -- 구매자 ID
                                 created_at  DATE   DEFAULT SYSDATE,                              -- 생성일
                                 last_message_at DATE,                                            -- 마지막 메시지 시각
                                 CONSTRAINT fk_tcr_trade FOREIGN KEY (trade_id)
                                     REFERENCES TKK.trade_post(trade_id),
                                 CONSTRAINT fk_tcr_buyer FOREIGN KEY (buyer_id)
                                     REFERENCES TKK.member(member_id),
                                 CONSTRAINT fk_tcr_seller FOREIGN KEY (seller_id)
                                     REFERENCES TKK.member(member_id)
);

-- 거래 채팅 메시지
CREATE TABLE TKK.trade_chat_message (
                                    message_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 메시지 PK
                                    room_id     NUMBER NOT NULL,                                     -- 채팅방 ID
                                    sender_id   NUMBER NOT NULL,                                     -- 보낸 사람 ID
                                    message     VARCHAR2(1000) NOT NULL,                             -- 메시지 내용
                                    created_at  DATE   DEFAULT SYSDATE,                              -- 전송 시각
                                    read_yn     CHAR(1) DEFAULT 'N',                                 -- 읽음 여부
                                    CONSTRAINT fk_tcm_room FOREIGN KEY (room_id)
                                        REFERENCES TKK.trade_chat_room(room_id),
                                    CONSTRAINT fk_tcm_sender FOREIGN KEY (sender_id)
                                        REFERENCES TKK.member(member_id)
);
--
-- ------------------------------------------------------------
-- -- 5. 알림 / 고객센터 / 공지 / FAQ / AI 상담 데이터
-- ------------------------------------------------------------
--
-- 알림 (댓글, 좋아요, 거래, 이벤트 등)
CREATE TABLE TKK.notification (
                              notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 알림 PK
                              member_id       NUMBER      NOT NULL,                                -- 대상 회원 ID
                              notif_type      VARCHAR2(30),                                        -- COMMENT/LIKE/TRADE/EVENT 등
                              message         VARCHAR2(255) NOT NULL,                              -- 알림 메시지
                              link_type       VARCHAR2(20),                                        -- POST/TRADE/STORE/POPUP 등
                              link_target_id  NUMBER,                                              -- 링크 대상 ID
                              read_yn         CHAR(1) DEFAULT 'N',                                 -- 읽음 여부
                              created_at      DATE   DEFAULT SYSDATE,                              -- 생성일
                              CONSTRAINT fk_notif_member FOREIGN KEY (member_id)
                                  REFERENCES TKK.member(member_id)
);

-- FAQ 카테고리 (AI 상담 분류: 매장/결제/계정/기타 등)
CREATE TABLE TKK.faq_category (
                              faq_category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- FAQ 카테고리 PK
                              name            VARCHAR2(50) NOT NULL                                -- 이름
);

-- FAQ 항목 (챗봇이 참고할 기본 Q&A)
CREATE TABLE TKK.faq (
                     faq_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- FAQ PK
                     faq_category_id NUMBER NOT NULL,                                     -- 카테고리 ID
                     question        VARCHAR2(255) NOT NULL,                              -- 질문
                     answer          CLOB          NOT NULL,                              -- 답변
                     sort_order      NUMBER        DEFAULT 1,                             -- 정렬 순서
                     CONSTRAINT fk_faq_category FOREIGN KEY (faq_category_id)
                         REFERENCES TKK.faq_category(faq_category_id)
);

-- 1:1 문의 (사람 상담 연결, 문의/버그/이벤트 관련)
CREATE TABLE TKK.inquiry (
                         inquiry_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 문의 PK
                         member_id       NUMBER,                                              -- 작성자 ID(비회원 NULL)
                         category        VARCHAR2(30),                                        -- 문의 유형 (이벤트/버그/계정 등)
                         title           VARCHAR2(200) NOT NULL,                              -- 제목
                         content         CLOB        NOT NULL,                                -- 내용
                         status          VARCHAR2(20) DEFAULT 'WAIT',                         -- WAIT/ANSWERING/DONE
                         answer_content  CLOB,                                                -- 답변 내용
                         created_at      DATE DEFAULT SYSDATE,                                -- 문의일
                         answered_at     DATE,                                                -- 답변일
                         CONSTRAINT fk_inquiry_member FOREIGN KEY (member_id)
                             REFERENCES TKK.member(member_id)
);
--
-- -- 서비스 공지/이벤트 안내 (마이페이지/이벤트 팝업)
CREATE TABLE TKK.service_notice (
                                notice_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 공지 PK
                                title           VARCHAR2(200) NOT NULL,                              -- 제목
                                content         CLOB          NOT NULL,                              -- 내용
                                notice_type     VARCHAR2(20)  DEFAULT 'NOTICE',                      -- NOTICE/EVENT/UPDATE
                                start_date      DATE,                                                -- 노출 시작일
                                end_date        DATE,                                                -- 노출 종료일
                                created_at      DATE DEFAULT SYSDATE                                 -- 등록일
);

--------------------------------------------------------
-- 1. 관리자 계정 테이블 + 시퀀스
--------------------------------------------------------
CREATE TABLE TKK.ADMIN_USER (
                            ADMIN_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            LOGIN_ID        VARCHAR2(50)      CONSTRAINT UQ_ADMIN_USER_LOGIN UNIQUE NOT NULL,
                            LOGIN_PW        VARCHAR2(200)     NOT NULL,
                            NAME            VARCHAR2(50)      NOT NULL,
                            EMAIL           VARCHAR2(100),
                            PHONE           VARCHAR2(20),
                            STATUS          CHAR(1)           DEFAULT 'Y' NOT NULL
                                CHECK (STATUS IN ('Y','N')), -- Y: 활성, N: 비활성
                            LAST_LOGIN_AT   DATE,
                            CREATED_AT      DATE              DEFAULT SYSDATE NOT NULL,
                            UPDATED_AT      DATE
);


--------------------------------------------------------
-- 2. 관리자 역할(권한) 테이블 + 시퀀스
--------------------------------------------------------
CREATE TABLE TKK.ADMIN_ROLE (
                            ROLE_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ROLE_CODE       VARCHAR2(30)     CONSTRAINT UQ_ADMIN_ROLE_CODE UNIQUE NOT NULL,
                            ROLE_NAME       VARCHAR2(50)     NOT NULL,
                            DESCRIPTION     VARCHAR2(200),
                            CREATED_AT      DATE             DEFAULT SYSDATE NOT NULL
);


--------------------------------------------------------
-- 3. 관리자-역할 매핑 테이블
--------------------------------------------------------
CREATE TABLE TKK.ADMIN_USER_ROLE (
                                 ADMIN_ID    NUMBER(10)   NOT NULL,
                                 ROLE_ID     NUMBER(10)   NOT NULL,
                                 CREATED_AT  DATE         DEFAULT SYSDATE NOT NULL,
                                 CONSTRAINT PK_ADMIN_USER_ROLE PRIMARY KEY (ADMIN_ID, ROLE_ID),
                                 CONSTRAINT FK_AUR_ADMIN
                                     FOREIGN KEY (ADMIN_ID) REFERENCES TKK.ADMIN_USER (ADMIN_ID),
                                 CONSTRAINT FK_AUR_ROLE
                                     FOREIGN KEY (ROLE_ID)  REFERENCES TKK.ADMIN_ROLE (ROLE_ID)
);

--------------------------------------------------------
-- 4. 관리자 활동 로그 테이블 + 시퀀스
--------------------------------------------------------
CREATE TABLE TKK.ADMIN_LOG (
                           LOG_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ADMIN_ID        NUMBER(10)       NOT NULL,
                           ACTION_TYPE     VARCHAR2(50)     NOT NULL,  -- 'LOGIN', 'DELETE_POST', ...
                           TARGET_TABLE    VARCHAR2(50),
                           TARGET_ID       NUMBER(20),
                           DESCRIPTION     VARCHAR2(400),
                           IP_ADDRESS      VARCHAR2(45),
                           CREATED_AT      DATE             DEFAULT SYSDATE NOT NULL,
                           CONSTRAINT FK_ADMIN_LOG_ADMIN
                               FOREIGN KEY (ADMIN_ID) REFERENCES TKK.ADMIN_USER (ADMIN_ID)
);

